# Python 연산자 연습

In [5]:
1 + 1

2

In [4]:
7 + 4

11

In [6]:
3 * 4

12

In [10]:
# 1이 아니고, 1.5로 나오네? Auto Casting?

3 / 2

1.5

In [9]:
1 == 1

True

In [11]:
10 % 2 == 0

True

In [12]:
11 % 2 == 0

False

In [13]:
(12 % 2 == 0) and (14 % 3 == 0)

False

In [22]:
(12 % 2 == 0) or (14 % 3 == 0)

True

In [15]:
a = 3
b = 5
a + b

8

In [16]:
a * b

15

In [17]:
a = 10
a + b

15

In [23]:
a = a + 1
print(a)

11


In [24]:
a = a + 2
print(a)

13


In [26]:
'1' + '2'

'12'

In [27]:
1 + 2

3

In [28]:
1 + int('2')

3

In [29]:
str(1) + '2'

'12'

In [30]:
print("Hello World!")

Hello World!


In [37]:
x = 3
y = 5
print("y = {1}, x = {0}".format(x,y))

y = 5, x = 3


In [39]:
# 출력의 format을 복잡하게 가져가야 할 때 선호

print("x = {x}, y = {y}".format(x=x,y=y))

x = 4.123456789, y = 7.987654321


In [42]:
x = 4.123456789
y = 7.987654321

print("x = {x:.3f}, y = {y:.5f}".format(x=x,y=y))

x = 4.123, y = 7.98765


In [43]:
message = "Hello World!"
print(message)

Hello World!


In [46]:
# 와우, -1 .. 역으로 출력하는건 처음이야 

message = "Hello World!"

print(message[0])
print(message[1])

print("---")

print(message[-1])
print(message[-2])

H
e
---
!
d


In [45]:
mesage = "Hello World!"

print(message[0:4])

Hell


In [49]:
print("H" in message)
print("A" in message)

True
False


In [50]:
odd = [1,3,5,7,9]
print(odd)

[1, 3, 5, 7, 9]


In [51]:
odd = [1,3,5,7,9]

print(odd[0])
print(odd[1])

print("---")

print(odd[-1])
print(odd[-2])

1
3
---
9
7


In [52]:
print(odd[0:4])

[1, 3, 5, 7]


In [53]:
print(1 in odd)
print(2 in odd)
print(3 in odd)

True
False
True


In [54]:
odd.append(11)
print(odd)

[1, 3, 5, 7, 9, 11]


In [55]:
odd = odd + [13, 15, 17, 19]
print(odd)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [56]:
odd[3] = -1
print(odd)

[1, 3, 5, -1, 9, 11, 13, 15, 17, 19]


In [58]:
message = "Hello World!"
print(message.split("o"))

['Hell', ' W', 'rld!']


In [60]:
message.upper()

'HELLO WORLD!'

In [61]:
message.lower()

'hello world!'

In [70]:
# format = key: value

dictionary = {
    'food': "음식",
    'kitchen': "주방",
    'apple': "사과"
}

print(dictionary)

{'food': '음식', 'kitchen': '주방', 'apple': '사과'}


In [68]:
print(dictionary.keys())

dict_keys(['food', 'kitchen', 'apple'])


In [69]:
print(dictionary.values())

dict_values(['음식', '주방', '사과'])


In [72]:
print(dictionary['food'])
print(dictionary['kitchen'])
print(dictionary['apple'])

음식
주방
사과


In [73]:
dictionary['banana'] = "바나나"
print(dictionary['banana'])

바나나


In [78]:
# key의 존재 여부 확인

print('food' in dictionary)
print('dog' in dictionary)

True
False


In [91]:
# 우앙 else if가 아니고 elif ..

age = 10

if age < 5:
  print("아이")
elif age < 18:
  print("학생")
else:
  print("어른")

학생


In [89]:
count = 0

while count < 10:
  print(count)

  count = count + 1

0
1
2
3
4
5
6
7
8
9


In [90]:
basket = ['apple', 'banana', 'chicken']

for stuff in basket:
  print(stuff)

apple
banana
chicken


In [95]:
for i in range(1, 11):
  if i == 5:
    continue
    
  if i == 8:
    break
    
  print(i)

1
2
3
4
6
7


In [96]:
double_list = []

for i in range(1, 11):
  if i == 5:
    continue
    
  if i == 8:
    break
    
  double = i * 2
  double_list.append(double)
    
print(double_list)

[2, 4, 6, 8, 12, 14]


In [97]:
def multiply(a, b):
  return a * b

print(multiply(3, 4))

12


In [98]:
def sign(n):
  if n > 0:
    return '양수'
  elif n < 0:
    return '음수'
  else:
    return '0'

print(sign(-1))
print(sign(2))
print(sign(0))

음수
양수
0


In [103]:
def factorial(n):
  result = 1

  for i in range(1, n+1):
    result = result * i
    
  return result
    
print(factorial(4))

24


In [107]:
def factorial(n):
  if n == 1:
    return 1
  else:
    return n * factorial(n-1)
    
print(factorial(4))

24


In [109]:
def cycle(n):
  result = [n]

  while n != 1:
    if n % 2 == 0:
      n = n / 2
    else:
      n = n * 3 + 1
    
    result.append(n)
    
  return result

print(cycle(3))

[3, 10, 5.0, 16.0, 8.0, 4.0, 2.0, 1.0]


In [110]:
def cycle(n):
  if n == 1:
    return [n]
  
  if n % 2 == 0:
    return [n] + cycle(n/2)
  else:
    return [n] + cycle(3 * n + 1)

cycle(3)

[3, 10, 5.0, 16.0, 8.0, 4.0, 2.0, 1.0]

In [113]:
def game369(maximum):
  result = []

  for n in range(1, maximum + 1):
    number = str(n)
    
    if '3' in number or '6' in number or '9' in number:
        result.append("clap!")
    else:
        result.append(number)
        
  return result

game369(40)

['1',
 '2',
 'clap!',
 '4',
 '5',
 'clap!',
 '7',
 '8',
 'clap!',
 '10',
 '11',
 '12',
 'clap!',
 '14',
 '15',
 'clap!',
 '17',
 '18',
 'clap!',
 '20',
 '21',
 '22',
 'clap!',
 '24',
 '25',
 'clap!',
 '27',
 '28',
 'clap!',
 'clap!',
 'clap!',
 'clap!',
 'clap!',
 'clap!',
 'clap!',
 'clap!',
 'clap!',
 'clap!',
 'clap!',
 '40']

In [117]:
def factorial(n):
  result = 1
    
  for i in range(1, n+1):
    result = result * i
        
  return result

factorial(4)

24

# Numpy

In [118]:
import numpy as np

In [119]:
da = [1, 2, 3]
na = np.array(da)

In [121]:
# Python 기본 array와 Numpy의 array 유사하게 동작

print(da[0])
print(da[1])

print('---')

print(na[0])
print(na[1])

1
2
---
1
2


In [124]:
da = [
  [1,2,3],
  [4,5,6],
  [7,8,9],
  [10,11,12]
]

na = np.array(da)
print(na)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [125]:
print(na.shape)

(4, 3)


In [128]:
print(da[0][0])
print(da[3][2])

print('---')

print(na[0,0])
print(na[3,2])

1
12
---
1
12


In [135]:
print(na[:,:])

print('---')

print(na[0,:])
print(na[1,:])
print(na[2,:])
print(na[3,:])

print('---')

print(na[:,0])
print(na[:,1])
print(na[:,2])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
---
[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]
---
[ 1  4  7 10]
[ 2  5  8 11]
[ 3  6  9 12]


In [136]:
print(na[0:2, :])
print(na[1:3, :])

[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [7 8 9]]


In [137]:
na > 7

array([[False, False, False],
       [False, False, False],
       [False,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [138]:
na[na>7]

array([ 8,  9, 10, 11, 12])

In [139]:
print(na + 1)
print(na - 2)
print(na * 3)
print(na / 4)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]
 [30 33 36]]
[[ 0.25  0.5   0.75]
 [ 1.    1.25  1.5 ]
 [ 1.75  2.    2.25]
 [ 2.5   2.75  3.  ]]


In [141]:
print(np.log(na))
print(np.exp(na))

[[ 0.          0.69314718  1.09861229]
 [ 1.38629436  1.60943791  1.79175947]
 [ 1.94591015  2.07944154  2.19722458]
 [ 2.30258509  2.39789527  2.48490665]]
[[  2.71828183e+00   7.38905610e+00   2.00855369e+01]
 [  5.45981500e+01   1.48413159e+02   4.03428793e+02]
 [  1.09663316e+03   2.98095799e+03   8.10308393e+03]
 [  2.20264658e+04   5.98741417e+04   1.62754791e+05]]


In [145]:
x = [
  [1,2],
  [3,4]
]

y = [
  [5,6],
  [7,8]
]

x = np.array(x)
y = np.array(y)

In [147]:
print(x + y)
print(x - y)
print(x * y)
print(x / y)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


# Pandas

In [148]:
import pandas as pd

In [154]:
# Pandas는 Excel과 역할이 거의 유사함
# 대량의 데이터에 최적화 되어 있어서, 용량이 많아져도 가능

pd.read_csv("data/train.csv")

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                                Rice, Master. Eugene    male   2.0      4   
17                        Williams, Mr. Charles Eugene    male   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                             Masselmani, Mrs. Fatima  female   NaN

In [218]:
# index(식별자) 지정

data = pd.read_csv("data/train.csv", index_col="PassengerId")
print(data.shape)

(891, 11)


In [160]:
data.head(20)

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
6                   0       3   
7                   0       1   
8                   0       3   
9                   1       3   
10                  1       2   
11                  1       3   
12                  1       1   
13                  0       3   
14                  0       3   
15                  0       3   
16                  1       2   
17                  0       3   
18                  1       2   
19                  0       3   
20                  1       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
6                                             Moran, Mr. James    male   NaN   
7                                      McCarthy, Mr. Timothy J    male  54.0   
8                               Palsson, Master. Gosta Leonard    male   2.0   
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
10                         Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   
11                             Sandstrom, Miss. Marguerite Rut  female   4.0   
12                                    Bonnell, Miss. Elizabeth  female  58.0   
13                              Saundercock, Mr. William Henry    male  20.0   
14                                 Andersson, Mr. Anders Johan    male  39.0   
15                        Vestrom, Miss. Hulda Amanda Adolfina  female  14.0   
16                            Hewlett, Mrs. (Mary D Kingcome)   female  55.0   
17                                        Rice, Master. Eugene    male   2.0   
18                                Williams, Mr. Charles Eugene    male   NaN   
19           Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0   
20                                     Masselmani, Mrs. Fatima  female   NaN   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S  
6                0      0            330877   8.4583   NaN        Q  
7                0      0             17463  51.8625   E46        S  
8                3      1            349909  21.0750   NaN        S  
9                0      2            347742  11.1333   NaN        S  
10               1      0            237736  30.0708   NaN        C  
11               1      1           PP 9549  16.7000    G6        S  
12               0      0            113783  26.5500  C103        S  
13               0      0         A/5. 2151   8.0500   NaN        S  
14               1      5            347082  31.2750   NaN        S  
15               0      0            350406   7.8542   NaN        S  
16               0      0            248706  16.0000   NaN        S  
17               4      1            382652  29.1250   NaN        Q  
18               0      0            244373  13.0000   NaN        S  
19               1      0            345763  18.0000   NaN        S  
20               0      0              2649   7.2250   

In [161]:
data.tail(15)

Survived  Pclass                                           Name  \
PassengerId                                                                    
877                 0       3                  Gustafsson, Mr. Alfred Ossian   
878                 0       3                           Petroff, Mr. Nedelio   
879                 0       3                             Laleff, Mr. Kristo   
880                 1       1  Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)   
881                 1       2   Shelley, Mrs. William (Imanita Parrish Hall)   
882                 0       3                             Markun, Mr. Johann   
883                 0       3                   Dahlberg, Miss. Gerda Ulrika   
884                 0       2                  Banfield, Mr. Frederick James   
885                 0       3                         Sutehall, Mr. Henry Jr   
886                 0       3           Rice, Mrs. William (Margaret Norton)   
887                 0       2                          Montvila, Rev. Juozas   
888                 1       1                   Graham, Miss. Margaret Edith   
889                 0       3       Johnston, Miss. Catherine Helen "Carrie"   
890                 1       1                          Behr, Mr. Karl Howell   
891                 0       3                            Dooley, Mr. Patrick   

                Sex   Age  SibSp  Parch            Ticket     Fare Cabin  \
PassengerId                                                                
877            male  20.0      0      0              7534   9.8458   NaN   
878            male  19.0      0      0            349212   7.8958   NaN   
879            male   NaN      0      0            349217   7.8958   NaN   
880          female  56.0      0      1             11767  83.1583   C50   
881          female  25.0      0      1            230433  26.0000   NaN   
882            male  33.0      0      0            349257   7.8958   NaN   
883          female  22.0      0      0              7552  10.5167   NaN   
884            male  28.0      0      0  C.A./SOTON 34068  10.5000   NaN   
885            male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN   
886          female  39.0      0      5            382652  29.1250   NaN   
887            male  27.0      0      0            211536  13.0000   NaN   
888          female  19.0      0      0            112053  30.0000   B42   
889          female   NaN      1      2        W./C. 6607  23.4500   NaN   
890            male  26.0      0      0            111369  30.0000  C148   
891            male  32.0      0      0            370376   7.7500   NaN   

            Embarked  
PassengerId           
877                S  
878                S  
879                S  
880                C  
881                S  
882                S  
883                S  
884                S  
885                S  
886                Q  
887                S  
888                S  
889                S  
890                C  
891                Q

In [162]:
print(data.index)

Int64Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
            ...
            882, 883, 884, 885, 886, 887, 888, 889, 890, 891],
           dtype='int64', name='PassengerId', length=891)


In [163]:
print(data.columns)

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Cabin', 'Embarked'],
      dtype='object')


In [167]:
# multi column을 가져오고 싶은 경우 대괄호를 한 번 더 적어줘야 함

data[["Sex", "Pclass", "Survived"]]

Sex  Pclass  Survived
PassengerId                          
1              male       3         0
2            female       1         1
3            female       3         1
4            female       1         1
5              male       3         0
6              male       3         0
7              male       1         0
8              male       3         0
9            female       3         1
10           female       2         1
11           female       3         1
12           female       1         1
13             male       3         0
14             male       3         0
15           female       3         0
16           female       2         1
17             male       3         0
18             male       2         1
19           female       3         0
20           female       3         1
21             male       2         0
22             male       2         1
23           female       3         1
24             male       1         1
25           female       3         0
26           female       3         1
27             male       3         0
28             male       1         0
29           female       3         1
30             male       3         0
...             ...     ...       ...
862            male       2         0
863          female       1         1
864          female       3         0
865            male       2         0
866          female       2         1
867          female       2         1
868            male       1         0
869            male       3         0
870            male       3         1
871            male       3         0
872          female       1         1
873            male       1         0
874            male       3         0
875          female       2         1
876          female       3         1
877            male       3         0
878            male       3         0
879            male       3         0
880          female       1         1
881          female       2         1
882            male       3         0
883          female       3         0
884            male       2         0
885            male       3         0
886          female       3         0
887            male       2         0
888          female       1         1
889          female       3         0
890            male       1         1
891            male       3         0

[891 rows x 3 columns]

In [168]:
# row를 가져오고 싶을 때에는, loc 활용

data.loc[0:7]

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
6                   0       3   
7                   0       1   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
6                                             Moran, Mr. James    male   NaN   
7                                      McCarthy, Mr. Timothy J    male  54.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S  
6                0      0            330877   8.4583   NaN        Q  
7                0      0             17463  51.8625   E46        S

In [183]:
data = data.reset_index()
data = data.set_index("Name")

In [184]:
data.head()

PassengerId  Survived  \
Name                                                                        
Braund, Mr. Owen Harris                                       1         0   
Cumings, Mrs. John Bradley (Florence Briggs Tha...            2         1   
Heikkinen, Miss. Laina                                        3         1   
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  4         1   
Allen, Mr. William Henry                                      5         0   

                                                    Pclass     Sex   Age  \
Name                                                                       
Braund, Mr. Owen Harris                                  3    male  22.0   
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  38.0   
Heikkinen, Miss. Laina                                   3  female  26.0   
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  35.0   
Allen, Mr. William Henry                                 3    male  35.0   

                                                    SibSp  Parch  \
Name                                                               
Braund, Mr. Owen Harris                                 1      0   
Cumings, Mrs. John Bradley (Florence Briggs Tha...      1      0   
Heikkinen, Miss. Laina                                  0      0   
Futrelle, Mrs. Jacques Heath (Lily May Peel)            1      0   
Allen, Mr. William Henry                                0      0   

                                                              Ticket     Fare  \
Name                                                                            
Braund, Mr. Owen Harris                                    A/5 21171   7.2500   
Cumings, Mrs. John Bradley (Florence Briggs Tha...          PC 17599  71.2833   
Heikkinen, Miss. Laina                              STON/O2. 3101282   7.9250   
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  113803  53.1000   
Allen, Mr. William Henry                                      373450   8.0500   

                                                   Cabin Embarked  
Name                                                               
Braund, Mr. Owen Harris                              NaN        S  
Cumings, Mrs. John Bradley (Florence Briggs Tha...   C85        C  
Heikkinen, Miss. Laina                               NaN        S  
Futrelle, Mrs. Jacques Heath (Lily May Peel)        C123        S  
Allen, Mr. William Henry                             NaN        S

In [181]:
data.loc["Braund, Mr. Owen Harris"]

Survived            0
Pclass              3
Sex              male
Age                22
SibSp               1
Parch               0
Ticket      A/5 21171
Fare             7.25
Cabin             NaN
Embarked            S
Name: Braund, Mr. Owen Harris, dtype: object

In [191]:
data.loc[["Braund, Mr. Owen Harris","Heikkinen, Miss. Laina", "Allen, Mr. William Henry"]]

PassengerId  Survived  Pclass     Sex   Age  SibSp  \
Name                                                                           
Braund, Mr. Owen Harris             1         0       3    male  22.0      1   
Heikkinen, Miss. Laina              3         1       3  female  26.0      0   
Allen, Mr. William Henry            5         0       3    male  35.0      0   

                          Parch            Ticket   Fare Cabin Embarked  
Name                                                                     
Braund, Mr. Owen Harris       0         A/5 21171  7.250   NaN        S  
Heikkinen, Miss. Laina        0  STON/O2. 3101282  7.925   NaN        S  
Allen, Mr. William Henry      0            373450  8.050   NaN        S

In [193]:
# 특정 row의 column 함께 가져오는 경우
# data.loc[[row index], [colums...]]

data.loc[["Braund, Mr. Owen Harris"],["Pclass", "Sex", "Survived"]]

Pclass   Sex  Survived
Name                                           
Braund, Mr. Owen Harris       3  male         0

In [194]:
data["Sex"] == "male"

Name
Braund, Mr. Owen Harris                                       True
Cumings, Mrs. John Bradley (Florence Briggs Thayer)          False
Heikkinen, Miss. Laina                                       False
Futrelle, Mrs. Jacques Heath (Lily May Peel)                 False
Allen, Mr. William Henry                                      True
Moran, Mr. James                                              True
McCarthy, Mr. Timothy J                                       True
Palsson, Master. Gosta Leonard                                True
Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)            False
Nasser, Mrs. Nicholas (Adele Achem)                          False
Sandstrom, Miss. Marguerite Rut                              False
Bonnell, Miss. Elizabeth                                     False
Saundercock, Mr. William Henry                                True
Andersson, Mr. Anders Johan                                   True
Vestrom, Miss. Hulda Amanda Adolfina                     

In [196]:
data[data["Sex"] == "male"]

PassengerId  Survived  Pclass   Sex  \
Name                                                                           
Braund, Mr. Owen Harris                            1         0       3  male   
Allen, Mr. William Henry                           5         0       3  male   
Moran, Mr. James                                   6         0       3  male   
McCarthy, Mr. Timothy J                            7         0       1  male   
Palsson, Master. Gosta Leonard                     8         0       3  male   
Saundercock, Mr. William Henry                    13         0       3  male   
Andersson, Mr. Anders Johan                       14         0       3  male   
Rice, Master. Eugene                              17         0       3  male   
Williams, Mr. Charles Eugene                      18         1       2  male   
Fynney, Mr. Joseph J                              21         0       2  male   
Beesley, Mr. Lawrence                             22         1       2  male   
Sloper, Mr. William Thompson                      24         1       1  male   
Emir, Mr. Farred Chehab                           27         0       3  male   
Fortune, Mr. Charles Alexander                    28         0       1  male   
Todoroff, Mr. Lalio                               30         0       3  male   
Uruchurtu, Don. Manuel E                          31         0       1  male   
Wheadon, Mr. Edward H                             34         0       2  male   
Meyer, Mr. Edgar Joseph                           35         0       1  male   
Holverson, Mr. Alexander Oskar                    36         0       1  male   
Mamee, Mr. Hanna                                  37         1       3  male   
Cann, Mr. Ernest Charles                          38         0       3  male   
Kraeff, Mr. Theodor                               43         0       3  male   
Rogers, Mr. William John                          46         0       3  male   
Lennon, Mr. Denis                                 47         0       3  male   
Samaan, Mr. Youssef                               49         0       3  male   
Panula, Master. Juha Niilo                        51         0       3  male   
Nosworthy, Mr. Richard Cater                      52         0       3  male   
Ostby, Mr. Engelhart Cornelius                    55         0       1  male   
Woolner, Mr. Hugh                                 56         1       1  male   
Novel, Mr. Mansouer                               58         0       3  male   
...                                              ...       ...     ...   ...   
Alhomaki, Mr. Ilmari Rudolf                      841         0       3  male   
Mudd, Mr. Thomas Charles                         842         0       2  male   
Lemberopolous, Mr. Peter L                       844         0       3  male   
Culumovic, Mr. Jeso                              845         0       3  male   
Abbing, Mr. Anthony                              846         0       3  male   
Sage, Mr. Douglas Bullen                         847         0       3  male   
Markoff, Mr. Marin                               848         0       3  male   
Harper, Rev. John                                849         0       2  male   
Andersson, Master. Sigvard Harald Elias          851         0       3  male   
Svensson, Mr. Johan                              852         0       3  male   
Daly, Mr. Peter Denis                            858         1       1  male   
Razi, Mr. Raihed                                 860         0       3  male   
Hansen, Mr. Claus Peter                          861         0       3  male   
Giles, Mr. Frederick Edward                      862         0       2  male   
Gill, Mr. John William                           865         0       2  male   
Roebling, Mr. Washington Augustus II             868         0       1  male   
van Melkebeke, Mr. Philemon                      869         0       3  male   
Johnson, Master. Harold Theodor          

In [197]:
data[data["Fare"] > 20]

PassengerId  Survived  \
Name                                                                        
Cumings, Mrs. John Bradley (Florence Briggs Tha...            2         1   
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  4         1   
McCarthy, Mr. Timothy J                                       7         0   
Palsson, Master. Gosta Leonard                                8         0   
Nasser, Mrs. Nicholas (Adele Achem)                          10         1   
Bonnell, Miss. Elizabeth                                     12         1   
Andersson, Mr. Anders Johan                                  14         0   
Rice, Master. Eugene                                         17         0   
Fynney, Mr. Joseph J                                         21         0   
Sloper, Mr. William Thompson                                 24         1   
Palsson, Miss. Torborg Danira                                25         0   
Asplund, Mrs. Carl Oscar (Selma Augusta Emilia ...           26         1   
Fortune, Mr. Charles Alexander                               28         0   
Uruchurtu, Don. Manuel E                                     31         0   
Spencer, Mrs. William Augustus (Marie Eugenie)               32         1   
Meyer, Mr. Edgar Joseph                                      35         0   
Holverson, Mr. Alexander Oskar                               36         0   
Turpin, Mrs. William John Robert (Dorothy Ann W...           42         0   
Laroche, Miss. Simonne Marie Anne Andree                     44         1   
Samaan, Mr. Youssef                                          49         0   
Panula, Master. Juha Niilo                                   51         0   
Harper, Mrs. Henry Sleeper (Myna Haxtun)                     53         1   
Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)           54         1   
Ostby, Mr. Engelhart Cornelius                               55         0   
Woolner, Mr. Hugh                                            56         1   
West, Miss. Constance Mirium                                 59         1   
Goodwin, Master. William Frederick                           60         0   
Icard, Miss. Amelie                                          62         1   
Harris, Mr. Henry Birkhardt                                  63         0   
Skoog, Master. Harald                                        64         0   
...                                                         ...       ...   
Mallet, Mr. Albert                                          818         0   
Skoog, Master. Karl Thorsten                                820         0   
Hays, Mrs. Charles Melville (Clara Jennings Gregg)          821         1   
Panula, Master. Urho Abraham                                825         0   
Lam, Mr. Len                                                827         0   
Mallet, Master. Andre                                       828         1   
Stone, Mrs. George Nelson (Martha Evelyn)                   830         1   
Compton, Miss. Sara Rebecca                                 836         1   
Chip, Mr. Chang                                             839         1   
Marechal, Mr. Pierre                                        840         1   
Serepeca, Miss. Augusta                                     843         1   
Sage, Mr. Douglas Bullen                                    847         0   
Harper, Rev. John                                           849         0   
Goldenberg, Mrs. Samuel L (Edwiga Grabowska)                850         1   
Andersson, Master. Sigvard Harald Elias                     851         0   
Lines, Miss. Mary Conover                                   854         1   
Carter, Mrs. Ernest Courtenay (Lilian Hughes)               855         0   
Wick, Mrs. George Dennick (Mary Hitchcock)                  857         1   
Daly, Mr. Peter Denis                                       858         1   
Swift, Mrs. Frederick Joel (Margaret Welles Bar.

In [199]:
data[data["Embarked"].isin(["Q","S"])]

PassengerId  Survived  \
Name                                                                        
Braund, Mr. Owen Harris                                       1         0   
Heikkinen, Miss. Laina                                        3         1   
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  4         1   
Allen, Mr. William Henry                                      5         0   
Moran, Mr. James                                              6         0   
McCarthy, Mr. Timothy J                                       7         0   
Palsson, Master. Gosta Leonard                                8         0   
Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)             9         1   
Sandstrom, Miss. Marguerite Rut                              11         1   
Bonnell, Miss. Elizabeth                                     12         1   
Saundercock, Mr. William Henry                               13         0   
Andersson, Mr. Anders Johan                                  14         0   
Vestrom, Miss. Hulda Amanda Adolfina                         15         0   
Hewlett, Mrs. (Mary D Kingcome)                              16         1   
Rice, Master. Eugene                                         17         0   
Williams, Mr. Charles Eugene                                 18         1   
Vander Planke, Mrs. Julius (Emelia Maria Vandem...           19         0   
Fynney, Mr. Joseph J                                         21         0   
Beesley, Mr. Lawrence                                        22         1   
McGowan, Miss. Anna "Annie"                                  23         1   
Sloper, Mr. William Thompson                                 24         1   
Palsson, Miss. Torborg Danira                                25         0   
Asplund, Mrs. Carl Oscar (Selma Augusta Emilia ...           26         1   
Fortune, Mr. Charles Alexander                               28         0   
O'Dwyer, Miss. Ellen "Nellie"                                29         1   
Todoroff, Mr. Lalio                                          30         0   
Glynn, Miss. Mary Agatha                                     33         1   
Wheadon, Mr. Edward H                                        34         0   
Holverson, Mr. Alexander Oskar                               36         0   
Cann, Mr. Ernest Charles                                     38         0   
...                                                         ...       ...   
Carter, Mrs. Ernest Courtenay (Lilian Hughes)               855         0   
Aks, Mrs. Sam (Leah Rosen)                                  856         1   
Wick, Mrs. George Dennick (Mary Hitchcock)                  857         1   
Daly, Mr. Peter Denis                                       858         1   
Hansen, Mr. Claus Peter                                     861         0   
Giles, Mr. Frederick Edward                                 862         0   
Swift, Mrs. Frederick Joel (Margaret Welles Bar...          863         1   
Sage, Miss. Dorothy Edith "Dolly"                           864         0   
Gill, Mr. John William                                      865         0   
Bystrom, Mrs. (Karolina)                                    866         1   
Roebling, Mr. Washington Augustus II                        868         0   
van Melkebeke, Mr. Philemon                                 869         0   
Johnson, Master. Harold Theodor                             870         1   
Balkic, Mr. Cerin                                           871         0   
Beckwith, Mrs. Richard Leonard (Sallie Monypeny)            872         1   
Carlsson, Mr. Frans Olof                                    873         0   
Vander Cruyssen, Mr. Victor                                 874         0   
Gustafsson, Mr. Alfred Ossian                               877         0   
Petroff, Mr. Nedelio                                        878         0   
Laleff, Mr. Kristo                              

In [200]:
data[data["Ticket"].str.contains("STON")]

PassengerId  Survived  \
Name                                                                        
Heikkinen, Miss. Laina                                        3         1   
Pekoniemi, Mr. Edvard                                       116         0   
Hakkarainen, Mrs. Pekka Pietari (Elin Matilda D...          143         1   
Sivola, Mr. Antti Wilhelm                                   174         0   
Honkanen, Miss. Eliina                                      217         1   
Maenpaa, Mr. Matti Alexanteri                               244         0   
Tikkanen, Mr. Juho                                          383         0   
Niskanen, Mr. Juha                                          401         1   
Hakkarainen, Mr. Pekka Pietari                              404         0   
Sundman, Mr. Johan Julian                                   415         1   
Kallio, Mr. Nikolai Erland                                  434         0   
Jussila, Mr. Eiriik                                         580         1   
Rintamaki, Mr. Matti                                        591         0   
Leinonen, Mr. Antti Gustaf                                  637         0   
Lindqvist, Mr. Eino William                                 665         1   
Ilmakangas, Miss. Pieta Sofia                               730         0   
Stranden, Mr. Juho                                          745         1   
Heininen, Miss. Wendla Maria                                817         0   

                                                    Pclass     Sex   Age  \
Name                                                                       
Heikkinen, Miss. Laina                                   3  female  26.0   
Pekoniemi, Mr. Edvard                                    3    male  21.0   
Hakkarainen, Mrs. Pekka Pietari (Elin Matilda D...       3  female  24.0   
Sivola, Mr. Antti Wilhelm                                3    male  21.0   
Honkanen, Miss. Eliina                                   3  female  27.0   
Maenpaa, Mr. Matti Alexanteri                            3    male  22.0   
Tikkanen, Mr. Juho                                       3    male  32.0   
Niskanen, Mr. Juha                                       3    male  39.0   
Hakkarainen, Mr. Pekka Pietari                           3    male  28.0   
Sundman, Mr. Johan Julian                                3    male  44.0   
Kallio, Mr. Nikolai Erland                               3    male  17.0   
Jussila, Mr. Eiriik                                      3    male  32.0   
Rintamaki, Mr. Matti                                     3    male  35.0   
Leinonen, Mr. Antti Gustaf                               3    male  32.0   
Lindqvist, Mr. Eino William                              3    male  20.0   
Ilmakangas, Miss. Pieta Sofia                            3  female  25.0   
Stranden, Mr. Juho                                       3    male  31.0   
Heininen, Miss. Wendla Maria                             3  female  23.0   

                                                    SibSp  Parch  \
Name                                                               
Heikkinen, Miss. Laina                                  0      0   
Pekoniemi, Mr. Edvard                                   0      0   
Hakkarainen, Mrs. Pekka Pietari (Elin Matilda D...      1      0   
Sivola, Mr. Antti Wilhelm                               0      0   
Honkanen, Miss. Eliina                                  0      0   
Maenpaa, Mr. Matti Alexanteri                           0      0   
Tikkanen, Mr. Juho                                      0      0   
Niskanen, Mr. Juha                                      0      0   
Hakkarainen, Mr. Pekka Pietari                          1      0   
Sundman, Mr. Johan Julian                               0      0   
Kallio, Mr. Nikolai Erland                              0      0   
Jussila, Mr. Eiriik                                     0      0   
Rintamaki, Mr. Matti                  

In [202]:
data[pd.isnull(data["Age"])]

PassengerId  Survived  Pclass  \
Name                                                                            
Moran, Mr. James                                          6         0       3   
Williams, Mr. Charles Eugene                             18         1       2   
Masselmani, Mrs. Fatima                                  20         1       3   
Emir, Mr. Farred Chehab                                  27         0       3   
O'Dwyer, Miss. Ellen "Nellie"                            29         1       3   
Todoroff, Mr. Lalio                                      30         0       3   
Spencer, Mrs. William Augustus (Marie Eugenie)           32         1       1   
Glynn, Miss. Mary Agatha                                 33         1       3   
Mamee, Mr. Hanna                                         37         1       3   
Kraeff, Mr. Theodor                                      43         0       3   
Rogers, Mr. William John                                 46         0       3   
Lennon, Mr. Denis                                        47         0       3   
O'Driscoll, Miss. Bridget                                48         1       3   
Samaan, Mr. Youssef                                      49         0       3   
Woolner, Mr. Hugh                                        56         1       1   
Stewart, Mr. Albert A                                    65         0       1   
Moubarek, Master. Gerios                                 66         1       3   
Staneff, Mr. Ivan                                        77         0       3   
Moutal, Mr. Rahamin Haim                                 78         0       3   
McDermott, Miss. Brigdet Delia                           83         1       3   
Slocovski, Mr. Selman Francis                            88         0       3   
Shorney, Mr. Charles Joseph                              96         0       3   
Petroff, Mr. Pastcho ("Pentcho")                        102         0       3   
Moss, Mr. Albert Johan                                  108         1       3   
Moran, Miss. Bertha                                     110         1       3   
Moore, Mr. Leonard Charles                              122         0       3   
McMahon, Mr. Martin                                     127         0       3   
Peter, Miss. Anna                                       129         1       3   
Boulos, Mrs. Joseph (Sultana)                           141         0       3   
Olsen, Mr. Ole Martin                                   155         0       3   
...                                                     ...       ...     ...   
McEvoy, Mr. Michael                                     719         0       3   
Mannion, Miss. Margareth                                728         1       3   
Knight, Mr. Robert J                                    733         0       2   
Ivanoff, Mr. Kanio                                      739         0       3   
Nankoff, Mr. Minko                                      740         0       3   
Hawksford, Mr. Walter James                             741         1       1   
Garfirth, Mr. John                                      761         0       3   
Brewe, Dr. Arthur Jackson                               767         0       1   
Moran, Mr. Daniel J                                     769         0       3   
Elias, Mr. Dibo                                         774         0       3   
Tobin, Mr. Roger                                        777         0       3   
Kilgannon, Mr. Thomas J                                 779         0       3   
Johnston, Mr. Andrew G                                  784         0       3   
Keane, Mr. Andrew "Andy"                                791         0       3   
Sage, Miss. Stella Anna                                 793         0       3   
Hoyt, Mr. William Fisher                                794         0       1   
Fry, Mr. Richard                                        816         0       1  

In [203]:
data[pd.isnull(data["Age"]) | (pd.isnull(data["Fare"]))] \

PassengerId  Survived  Pclass  \
Name                                                                            
Moran, Mr. James                                          6         0       3   
Williams, Mr. Charles Eugene                             18         1       2   
Masselmani, Mrs. Fatima                                  20         1       3   
Emir, Mr. Farred Chehab                                  27         0       3   
O'Dwyer, Miss. Ellen "Nellie"                            29         1       3   
Todoroff, Mr. Lalio                                      30         0       3   
Spencer, Mrs. William Augustus (Marie Eugenie)           32         1       1   
Glynn, Miss. Mary Agatha                                 33         1       3   
Mamee, Mr. Hanna                                         37         1       3   
Kraeff, Mr. Theodor                                      43         0       3   
Rogers, Mr. William John                                 46         0       3   
Lennon, Mr. Denis                                        47         0       3   
O'Driscoll, Miss. Bridget                                48         1       3   
Samaan, Mr. Youssef                                      49         0       3   
Woolner, Mr. Hugh                                        56         1       1   
Stewart, Mr. Albert A                                    65         0       1   
Moubarek, Master. Gerios                                 66         1       3   
Staneff, Mr. Ivan                                        77         0       3   
Moutal, Mr. Rahamin Haim                                 78         0       3   
McDermott, Miss. Brigdet Delia                           83         1       3   
Slocovski, Mr. Selman Francis                            88         0       3   
Shorney, Mr. Charles Joseph                              96         0       3   
Petroff, Mr. Pastcho ("Pentcho")                        102         0       3   
Moss, Mr. Albert Johan                                  108         1       3   
Moran, Miss. Bertha                                     110         1       3   
Moore, Mr. Leonard Charles                              122         0       3   
McMahon, Mr. Martin                                     127         0       3   
Peter, Miss. Anna                                       129         1       3   
Boulos, Mrs. Joseph (Sultana)                           141         0       3   
Olsen, Mr. Ole Martin                                   155         0       3   
...                                                     ...       ...     ...   
McEvoy, Mr. Michael                                     719         0       3   
Mannion, Miss. Margareth                                728         1       3   
Knight, Mr. Robert J                                    733         0       2   
Ivanoff, Mr. Kanio                                      739         0       3   
Nankoff, Mr. Minko                                      740         0       3   
Hawksford, Mr. Walter James                             741         1       1   
Garfirth, Mr. John                                      761         0       3   
Brewe, Dr. Arthur Jackson                               767         0       1   
Moran, Mr. Daniel J                                     769         0       3   
Elias, Mr. Dibo                                         774         0       3   
Tobin, Mr. Roger                                        777         0       3   
Kilgannon, Mr. Thomas J                                 779         0       3   
Johnston, Mr. Andrew G                                  784         0       3   
Keane, Mr. Andrew "Andy"                                791         0       3   
Sage, Miss. Stella Anna                                 793         0       3   
Hoyt, Mr. William Fisher                                794         0       1   
Fry, Mr. Richard                                        816         0       1  

In [204]:
data[pd.isnull(data["Age"]) & (pd.isnull(data["Fare"]))]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [212]:
data.iloc[0]
# data["FamilyName"] = data["Name"].apply(lambda name: name.split(",")[0])

PassengerId            1
Survived               0
Pclass                 3
Sex                 male
Age                   22
SibSp                  1
Parch                  0
Ticket         A/5 21171
Fare                7.25
Cabin                NaN
Embarked               S
Name: Braund, Mr. Owen Harris, dtype: object

In [214]:
data["Fare"].value_counts()

8.0500      43
13.0000     42
7.8958      38
7.7500      34
26.0000     31
10.5000     24
7.9250      18
7.7750      16
26.5500     15
0.0000      15
7.2292      15
7.8542      13
8.6625      13
7.2500      13
7.2250      12
16.1000      9
9.5000       9
24.1500      8
15.5000      8
56.4958      7
52.0000      7
14.5000      7
14.4542      7
69.5500      7
7.0500       7
31.2750      7
46.9000      6
30.0000      6
7.7958       6
39.6875      6
            ..
7.1417       1
42.4000      1
211.5000     1
12.2750      1
61.1750      1
8.4333       1
51.4792      1
7.8875       1
8.6833       1
7.5208       1
34.6542      1
28.7125      1
25.5875      1
7.7292       1
12.2875      1
8.6542       1
8.7125       1
61.3792      1
6.9500       1
9.8417       1
8.3000       1
13.7917      1
9.4750       1
13.4167      1
26.3875      1
8.4583       1
9.8375       1
8.3625       1
14.1083      1
17.4000      1
Name: Fare, dtype: int64

In [219]:
data["foo1"] = 1
data["foo2"] = 2
data["foo3"] = 3

data.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  foo1  \
PassengerId                                                                 
1                1      0         A/5 21171   7.2500   NaN        S     1   
2                1      0          PC 17599  71.2833   C85        C     1   
3                0      0  STON/O2. 3101282   7.9250   NaN        S     1   
4                1      0            113803  53.1000  C123        S     1   
5                0      0            373450   8.0500   NaN        S     1   

             foo2  foo3  
PassengerId              
1               2     3  
2               2     3  
3               2     3  
4               2     3  
5               2     3

In [222]:
# axis = 0 --> row, axis = 1 --> col

# data = data.drop("foo2", axis=1)
# data.drop("foo2", axis=1, inplace=True)

data.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  foo1  \
PassengerId                                                                 
1                1      0         A/5 21171   7.2500   NaN        S     1   
2                1      0          PC 17599  71.2833   C85        C     1   
3                0      0  STON/O2. 3101282   7.9250   NaN        S     1   
4                1      0            113803  53.1000  C123        S     1   
5                0      0            373450   8.0500   NaN        S     1   

             foo3  
PassengerId        
1               3  
2               3  
3               3  
4               3  
5               3

In [223]:
data["Survived(bool)"] = data["Survived"] == 1

In [224]:
data.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  foo1  \
PassengerId                                                                 
1                1      0         A/5 21171   7.2500   NaN        S     1   
2                1      0          PC 17599  71.2833   C85        C     1   
3                0      0  STON/O2. 3101282   7.9250   NaN        S     1   
4                1      0            113803  53.1000  C123        S     1   
5                0      0            373450   8.0500   NaN        S     1   

             foo3 Survived(bool)  
PassengerId                       
1               3          False  
2               3           True  
3               3           True  
4               3           True  
5               3          False

In [225]:
print(data["Fare"].mean())

32.2042079685746


In [226]:
print(data["Age"].min())

0.42


In [227]:
print(data["Age"].max())

80.0


In [229]:
data["Family(count)"] = (data["SibSp"] + data["Parch"])

In [230]:
data.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  foo1  \
PassengerId                                                                 
1                1      0         A/5 21171   7.2500   NaN        S     1   
2                1      0          PC 17599  71.2833   C85        C     1   
3                0      0  STON/O2. 3101282   7.9250   NaN        S     1   
4                1      0            113803  53.1000  C123        S     1   
5                0      0            373450   8.0500   NaN        S     1   

             foo3 Survived(bool)  Family(count)  
PassengerId                                      
1               3          False              1  
2               3           True              1  
3               3           True              0  
4               3           True              1  
5               3          False              0

In [232]:
embarked = pd.get_dummies(data["Embarked"], prefix="Embarked")

In [233]:
embarked.head()

Embarked_C  Embarked_Q  Embarked_S
PassengerId                                    
1                     0           0           1
2                     1           0           0
3                     0           0           1
4                     0           0           1
5                     0           0           1

In [234]:
pd.concat([data, embarked], axis=1)

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
6                   0       3   
7                   0       1   
8                   0       3   
9                   1       3   
10                  1       2   
11                  1       3   
12                  1       1   
13                  0       3   
14                  0       3   
15                  0       3   
16                  1       2   
17                  0       3   
18                  1       2   
19                  0       3   
20                  1       3   
21                  0       2   
22                  1       2   
23                  1       3   
24                  1       1   
25                  0       3   
26                  1       3   
27                  0       3   
28                  0       1   
29                  1       3   
30                  0       3   
...               ...     ...   
862                 0       2   
863                 1       1   
864                 0       3   
865                 0       2   
866                 1       2   
867                 1       2   
868                 0       1   
869                 0       3   
870                 1       3   
871                 0       3   
872                 1       1   
873                 0       1   
874                 0       3   
875                 1       2   
876                 1       3   
877                 0       3   
878                 0       3   
879                 0       3   
880                 1       1   
881                 1       2   
882                 0       3   
883                 0       3   
884                 0       2   
885                 0       3   
886                 0       3   
887                 0       2   
888                 1       1   
889                 0       3   
890                 1       1   
891                 0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
6                                             Moran, Mr. James    male   NaN   
7                                      McCarthy, Mr. Timothy J    male  54.0   
8                               Palsson, Master. Gosta Leonard    male   2.0   
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
10                         Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   
11                             Sandstrom, Miss. Marguerite Rut  female   4.0   
12                                    Bonnell, Miss. Elizabeth  female  58.0   
13                              Saundercock, Mr. William Henry    male  20.0   
14                                 Andersson, Mr. Anders Johan    male  39.0   
15                        Vestrom, Miss. Hulda Amanda Adolfina  female  14.0   
16                            Hewlett, Mrs. (Mary D Kingcome)   female  55.0   
17                                        Rice, Master. Eugene    male   2.0   
18                                Williams, Mr. Charles Eugene    male   NaN   
19           Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0   
20                                     Masselmani, Mrs. Fatima  female   NaN   
21                                        Fynney, Mr. Joseph J    male  35.0   
22                                       Beesley, Mr. Lawrence    male  34.0   
23           

In [235]:
data = data.reset_index()
data = data.set_index("Name")

In [236]:
data.head()

PassengerId  Survived  \
Name                                                                        
Braund, Mr. Owen Harris                                       1         0   
Cumings, Mrs. John Bradley (Florence Briggs Tha...            2         1   
Heikkinen, Miss. Laina                                        3         1   
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  4         1   
Allen, Mr. William Henry                                      5         0   

                                                    Pclass     Sex   Age  \
Name                                                                       
Braund, Mr. Owen Harris                                  3    male  22.0   
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  38.0   
Heikkinen, Miss. Laina                                   3  female  26.0   
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  35.0   
Allen, Mr. William Henry                                 3    male  35.0   

                                                    SibSp  Parch  \
Name                                                               
Braund, Mr. Owen Harris                                 1      0   
Cumings, Mrs. John Bradley (Florence Briggs Tha...      1      0   
Heikkinen, Miss. Laina                                  0      0   
Futrelle, Mrs. Jacques Heath (Lily May Peel)            1      0   
Allen, Mr. William Henry                                0      0   

                                                              Ticket     Fare  \
Name                                                                            
Braund, Mr. Owen Harris                                    A/5 21171   7.2500   
Cumings, Mrs. John Bradley (Florence Briggs Tha...          PC 17599  71.2833   
Heikkinen, Miss. Laina                              STON/O2. 3101282   7.9250   
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  113803  53.1000   
Allen, Mr. William Henry                                      373450   8.0500   

                                                   Cabin Embarked  foo1  foo3  \
Name                                                                            
Braund, Mr. Owen Harris                              NaN        S     1     3   
Cumings, Mrs. John Bradley (Florence Briggs Tha...   C85        C     1     3   
Heikkinen, Miss. Laina                               NaN        S     1     3   
Futrelle, Mrs. Jacques Heath (Lily May Peel)        C123        S     1     3   
Allen, Mr. William Henry                             NaN        S     1     3   

                                                   Survived(bool)  \
Name                                                                
Braund, Mr. Owen Harris                                     False   
Cumings, Mrs. John Bradley (Florence Briggs Tha...           True   
Heikkinen, Miss. Laina                                       True   
Futrelle, Mrs. Jacques Heath (Lily May Peel)                 True   
Allen, Mr. William Henry                                    False   

                                                    Family(count)  
Name                                                               
Braund, Mr. Owen Harris                                         1  
Cumings, Mrs. John Bradley (Florence Briggs Tha...              1  
Heikkinen, Miss. Laina                                          0  
Futrelle, Mrs. Jacques Heath (Lily May Peel)                    1  
Allen, Mr. William Henry                                        0

In [237]:
embarked = pd.get_dummies(data["Embarked"], prefix="Embarked")
pd.concat([data, embarked], axis=1)

PassengerId  Survived  \
Name                                                                        
Braund, Mr. Owen Harris                                       1         0   
Cumings, Mrs. John Bradley (Florence Briggs Tha...            2         1   
Heikkinen, Miss. Laina                                        3         1   
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  4         1   
Allen, Mr. William Henry                                      5         0   
Moran, Mr. James                                              6         0   
McCarthy, Mr. Timothy J                                       7         0   
Palsson, Master. Gosta Leonard                                8         0   
Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)             9         1   
Nasser, Mrs. Nicholas (Adele Achem)                          10         1   
Sandstrom, Miss. Marguerite Rut                              11         1   
Bonnell, Miss. Elizabeth                                     12         1   
Saundercock, Mr. William Henry                               13         0   
Andersson, Mr. Anders Johan                                  14         0   
Vestrom, Miss. Hulda Amanda Adolfina                         15         0   
Hewlett, Mrs. (Mary D Kingcome)                              16         1   
Rice, Master. Eugene                                         17         0   
Williams, Mr. Charles Eugene                                 18         1   
Vander Planke, Mrs. Julius (Emelia Maria Vandem...           19         0   
Masselmani, Mrs. Fatima                                      20         1   
Fynney, Mr. Joseph J                                         21         0   
Beesley, Mr. Lawrence                                        22         1   
McGowan, Miss. Anna "Annie"                                  23         1   
Sloper, Mr. William Thompson                                 24         1   
Palsson, Miss. Torborg Danira                                25         0   
Asplund, Mrs. Carl Oscar (Selma Augusta Emilia ...           26         1   
Emir, Mr. Farred Chehab                                      27         0   
Fortune, Mr. Charles Alexander                               28         0   
O'Dwyer, Miss. Ellen "Nellie"                                29         1   
Todoroff, Mr. Lalio                                          30         0   
...                                                         ...       ...   
Giles, Mr. Frederick Edward                                 862         0   
Swift, Mrs. Frederick Joel (Margaret Welles Bar...          863         1   
Sage, Miss. Dorothy Edith "Dolly"                           864         0   
Gill, Mr. John William                                      865         0   
Bystrom, Mrs. (Karolina)                                    866         1   
Duran y More, Miss. Asuncion                                867         1   
Roebling, Mr. Washington Augustus II                        868         0   
van Melkebeke, Mr. Philemon                                 869         0   
Johnson, Master. Harold Theodor                             870         1   
Balkic, Mr. Cerin                                           871         0   
Beckwith, Mrs. Richard Leonard (Sallie Monypeny)            872         1   
Carlsson, Mr. Frans Olof                                    873         0   
Vander Cruyssen, Mr. Victor                                 874         0   
Abelson, Mrs. Samuel (Hannah Wizosky)                       875         1   
Najib, Miss. Adele Kiamie "Jane"                            876         1   
Gustafsson, Mr. Alfred Ossian                               877         0   
Petroff, Mr. Nedelio                                        878         0   
Laleff, Mr. Kristo                                          879         0   
Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)               880         1   
Shelley, Mrs. William (Imanita Parrish Hall)    

In [238]:
train = pd.read_csv("data/train.csv")
test = pd.read_csv("data/test.csv")

pd.concat([train,test])

Age        Cabin Embarked      Fare  \
0    22.0          NaN        S    7.2500   
1    38.0          C85        C   71.2833   
2    26.0          NaN        S    7.9250   
3    35.0         C123        S   53.1000   
4    35.0          NaN        S    8.0500   
5     NaN          NaN        Q    8.4583   
6    54.0          E46        S   51.8625   
7     2.0          NaN        S   21.0750   
8    27.0          NaN        S   11.1333   
9    14.0          NaN        C   30.0708   
10    4.0           G6        S   16.7000   
11   58.0         C103        S   26.5500   
12   20.0          NaN        S    8.0500   
13   39.0          NaN        S   31.2750   
14   14.0          NaN        S    7.8542   
15   55.0          NaN        S   16.0000   
16    2.0          NaN        Q   29.1250   
17    NaN          NaN        S   13.0000   
18   31.0          NaN        S   18.0000   
19    NaN          NaN        C    7.2250   
20   35.0          NaN        S   26.0000   
21   34.0          D56        S   13.0000   
22   15.0          NaN        Q    8.0292   
23   28.0           A6        S   35.5000   
24    8.0          NaN        S   21.0750   
25   38.0          NaN        S   31.3875   
26    NaN          NaN        C    7.2250   
27   19.0  C23 C25 C27        S  263.0000   
28    NaN          NaN        Q    7.8792   
29    NaN          NaN        S    7.8958   
..    ...          ...      ...       ...   
388  21.0          NaN        Q    7.7500   
389   6.0          NaN        S   21.0750   
390  23.0          B24        S   93.5000   
391  51.0          D28        S   39.4000   
392  13.0          NaN        S   20.2500   
393  47.0          NaN        S   10.5000   
394  29.0          NaN        S   22.0250   
395  18.0          C31        S   60.0000   
396  24.0          NaN        Q    7.2500   
397  48.0          B41        C   79.2000   
398  22.0          NaN        S    7.7750   
399  31.0          NaN        Q    7.7333   
400  30.0           C7        S  164.8667   
401  38.0          NaN        S   21.0000   
402  22.0          NaN        C   59.4000   
403  17.0          NaN        S   47.1000   
404  43.0          D40        C   27.7208   
405  20.0          D38        C   13.8625   
406  23.0          NaN        S   10.5000   
407  50.0          C80        C  211.5000   
408   NaN          NaN        Q    7.7208   
409   3.0          NaN        S   13.7750   
410   NaN          NaN        Q    7.7500   
411  37.0          C78        Q   90.0000   
412  28.0          NaN        S    7.7750   
413   NaN          NaN        S    8.0500   
414  39.0         C105        C  108.9000   
415  38.5          NaN        S    7.2500   
416   NaN          NaN        S    8.0500   
417   NaN          NaN        C   22.3583   

                                                  Name  Parch  PassengerId  \
0                              Braund, Mr. Owen Harris      0            1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...      0            2   
2                               Heikkinen, Miss. Laina      0            3   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)      0            4   
4                             Allen, Mr. William Henry      0            5   
5                                     Moran, Mr. James      0            6   
6                              McCarthy, Mr. Timothy J      0            7   
7                       Palsson, Master. Gosta Leonard      1            8   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)      2            9   
9                  Nasser, Mrs. Nicholas (Adele Achem)      0           10   
10                     Sandstrom, Miss. Marguerite Rut      1           11   
11                            Bonnell, Miss. Elizabeth      0           12   
12                      Saundercock, Mr. William Henry      0           13   
13                         Andersson, Mr. Anders Johan      5           14   
14                Vestrom, Miss. Hulda Amanda

In [239]:
data["Ticket"].apply(lambda ticket: ticket[0:3])

Name
Braund, Mr. Owen Harris                                      A/5
Cumings, Mrs. John Bradley (Florence Briggs Thayer)          PC 
Heikkinen, Miss. Laina                                       STO
Futrelle, Mrs. Jacques Heath (Lily May Peel)                 113
Allen, Mr. William Henry                                     373
Moran, Mr. James                                             330
McCarthy, Mr. Timothy J                                      174
Palsson, Master. Gosta Leonard                               349
Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)            347
Nasser, Mrs. Nicholas (Adele Achem)                          237
Sandstrom, Miss. Marguerite Rut                              PP 
Bonnell, Miss. Elizabeth                                     113
Saundercock, Mr. William Henry                               A/5
Andersson, Mr. Anders Johan                                  347
Vestrom, Miss. Hulda Amanda Adolfina                         350
Hewlett, Mrs. (Mary 

In [243]:
data.to_csv("data/train(modified).csv")

In [244]:
modified_data = pd.read_csv("data/train(modified).csv")

In [245]:
print(modified_data.shape)
modified_data.head()

(891, 16)


Name  PassengerId  Survived  \
0                            Braund, Mr. Owen Harris            1         0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...            2         1   
2                             Heikkinen, Miss. Laina            3         1   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)            4         1   
4                           Allen, Mr. William Henry            5         0   

   Pclass     Sex   Age  SibSp  Parch            Ticket     Fare Cabin  \
0       3    male  22.0      1      0         A/5 21171   7.2500   NaN   
1       1  female  38.0      1      0          PC 17599  71.2833   C85   
2       3  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN   
3       1  female  35.0      1      0            113803  53.1000  C123   
4       3    male  35.0      0      0            373450   8.0500   NaN   

  Embarked  foo1  foo3 Survived(bool)  Family(count)  
0        S     1     3          False              1  
1        C     1     3           True              1  
2        S     1     3           True              0  
3        S     1     3           True              1  
4        S     1     3          False              0

In [246]:
import seaborn as sns

In [250]:
sns.distplot(data=data, x="Pclass", )

TypeError: distplot() got an unexpected keyword argument 'data'